spring.application.name=java-backend

# Spring Boot 配置
app.release-label=local
# 启用 Actuator 的 liveness 与 readiness 健康组。
management.endpoint.health.probes.enabled=true
# 除了 Actuator 默认路径，也在主应用端口提供 /livez 和 /readyz 路径
management.endpoint.health.probes.add-additional-paths=true

# 数据源配置
spring.datasource.url=jdbc:h2:mem:versiondb;DB_CLOSE_DELAY=-1
# 数据源用户名
spring.datasource.username=sa
# 数据源密码
spring.datasource.password=
# 数据源驱动类名
spring.jpa.hibernate.ddl-auto=create-drop
# 延迟初始化数据源，确保在应用启动时创建数据库
spring.jpa.defer-datasource-initialization=true
# 数据源初始化模式
spring.sql.init.mode=always