spring.application.name=java-backend

# Spring Boot 配置
app.release-label=local
# 启用 Actuator 的 liveness 与 readiness 健康组。
management.endpoint.health.probes.enabled=true
# 除了 Actuator 默认路径，也在主应用端口提供 /livez 和 /readyz 路径
management.endpoint.health.probes.add-additional-paths=true
